name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Install wasm-tools
        run: dotnet workload install wasm-tools

      - name: Publish
        run: dotnet publish CharmonePortfolio/CharmonePortfolio.csproj -c Release -o release

      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Add CNAME
        run: echo 'charmonestrauss.co.za' > release/wwwroot/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
          force_orphan: true